.changeset/wicked-masks-tell.md, packages/agents-openai/src/openaiChatCompletionsModel.ts
=> Fix handoff for chat completions mode

.changeset/fix-schema-version-serialization.md, packages/agents-core/src/runState.ts, packages/agents-core/test/runState.test.ts
**Summary**
export CURRENT_SCHEMA_VERSION
use the constant when serializing a RunState
update tests to reference the constant
**Testing**
pnpm -r build-check
CI=1 pnpm test
pnpm lint
=> fix: schema version serialization

.changeset/hip-needles-love.md, packages/agents-core/src/runImplementation.ts, packages/agents-core/test/run.test.ts, packages/agents-core/test/runImplementation.test.ts, packages/agents-core/test/runState.test.ts, packages/agents-core/test/shims/mcp-stdio/node.test.ts, packages/agents-core/test/stubs.ts, packages/agents-extensions/test/aiSdk.test.ts, packages/agents-extensions/test/index.test.ts
This pull request reduces unnecessary stdout outputs during `pnpm test` execution. Not yet eliminated (mainly agents-realtime has a few more outputs that should be managed properly) but this PR definitely improves it.
Current outputs:
```
> CI=1 NODE_ENV=test vitest
RUN  v3.1.1 /path-to/openai-agents-js
✓  @openai/agents-realtime  test/utils.test.ts (8 tests) 2ms
✓  @openai/agents-core  test/tracing.test.ts (10 tests) 5ms
✓  @openai/agents-openai  test/openaiChatCompletionsConverter.test.ts (14 tests) 3ms
✓  @openai/agents-core  test/items.test.ts (8 tests) 2ms
✓  @openai/agents-core  test/runState.test.ts (14 tests) 6ms
✓  @openai/agents-openai  test/openaiChatCompletionsModel.test.ts (8 tests) 6ms
✓  @openai/agents-realtime  test/openaiRealtimeWebRtc.test.ts (6 tests) 7ms
✓ …
```
=> fix: Reduce warning/stdout outputs during test executions

.changeset/quiet-flies-march.md, packages/agents-core/src/shims/shims-browser.ts
Fix a bug when call `randomUUID` in the browser.
=> fix(shims): Bind crypto to randomUUID

.changeset/purple-oranges-shout.md, packages/agents-core/src/shims/shims-browser.ts
Some code like `packages/agents-core/src/tracing/context.ts:25` will call this function.
=> fix(shims): Naively polyfill AsyncLocalStorage in browser

.changeset/honest-lands-pump.md, packages/agents-core/src/index.ts, packages/agents-core/src/tracing/index.ts, packages/agents-core/src/tracing/provider.ts
Ensures cleanup occurs and exit occurs for each provider.
I tested on the basic example, pressing `^c` while the agent processed.
Fixes #44
=> fix(agents-core): process listeners

docs/src/components/Hero.astro, docs/src/content/docs/index.mdx, docs/src/content/docs/ja/index.mdx, docs/src/styles/global.css
This is not implementing the new design entirely and is instead a first iteration
=> docs: redesign to fit more new centralized design

docs/src/content/docs/guides/running-agents.mdx
This PR fixes the "Streaming guide" link on [Running-agents](https://openai.github.io/openai-agents-js/guides/running-agents/#streaming) page.
Recording of the issue
https://github.com/user-attachments/assets/30ba0718-6345-4a60-8f15-1d5d828af56f
Previous Link:  /guides/streaming
Updated Link: /openai-agents-js/guides/streaming
=> fix: streaming guide link on running-agents page

.changeset/wild-stars-teach.md, examples/mcp/hosted-mcp-approvals.ts, examples/mcp/hosted-mcp-human-in-the-loop.ts, examples/mcp/hosted-mcp-on-approval.ts, examples/mcp/hosted-mcp-simple.ts, examples/mcp/package.json, packages/agents-core/src/index.ts, packages/agents-core/src/items.ts, packages/agents-core/src/runContext.ts, packages/agents-core/src/runImplementation.ts, packages/agents-core/src/runState.ts, packages/agents-core/src/tool.ts, packages/agents-core/src/types/index.ts, packages/agents-core/src/types/protocol.ts, packages/agents-core/src/types/providerData.ts, packages/agents-core/test/run.test.ts, packages/agents-core/test/runState.test.ts, packages/agents-core/test/tool.test.ts, packages/agents-openai/src/openaiResponsesModel.ts, packages/agents-openai/src/tools.ts, packages/agents-openai/src/types/providerData.ts, packages/agents-openai/src/utils/providerData.ts, packages/agents-openai/test/openaiResponsesModel.helpers.test.ts, packages/agents-openai/test/utils/providerData.test.ts, packages/agents-realtime/src/realtimeSession.ts
This pull request resolves #23
=> Fix #23 Add Hosted MCP server tool support

.changeset/crazy-coats-give.md, examples/mcp/package.json, examples/mcp/streamable-http-example.ts, packages/agents-core/src/index.ts, packages/agents-core/src/mcp.ts, packages/agents-core/src/shims/mcp-server/browser.ts, packages/agents-core/src/shims/mcp-server/node.ts, packages/agents-core/src/shims/shims-browser.ts, packages/agents-core/src/shims/shims-node.ts, packages/agents-core/src/shims/shims-workerd.ts, packages/agents-core/test/mcpCache.test.ts, packages/agents-core/test/shims/mcp-server/browser.test.ts, packages/agents-core/test/shims/mcp-server/node.test.ts
This pull request adds remote MCP server support (Streamable HTTP) to the `mcpServers` parameter of the Agent constructor. Having this change resolves #78. We don't plan to support SSE, which is now a legacy protocol.
=> Add remote MCP server (Streamable HTTP) support; fixes #78

.changeset/eighty-dingos-pump.md, examples/mcp/filesystem-example.ts, examples/mcp/hosted-mcp-human-in-the-loop.ts, examples/mcp/hosted-mcp-on-approval.ts, examples/mcp/hosted-mcp-simple.ts, packages/agents-core/src/tool.ts, packages/agents-core/src/types/providerData.ts, packages/agents-openai/src/openaiResponsesModel.ts
This pull request adds two more parameters for hosted mcp server tool initialization, which are missing in #33 :
- allowed_tools
- headers
=> Add allowed_tools and headers to hosted mcp server factory method

.changeset/clever-needles-flow.md, packages/agents-core/src/tracing/spans.ts, packages/agents-core/test/tracing.test.ts, packages/agents-openai/src/openaiResponsesModel.ts
Adds `_response` as an attribute to `ResponseSpanData` for use by third-party tracing integrations. 
Adds a test to verify that the new attribute does not get exported to the default tracer.
=> Export OpenAI Response object on ResponseSpanData.

examples/agent-patterns/routing.ts, examples/basic/index.ts, examples/basic/local-image.ts, examples/customer-service/index.ts, examples/docs/models/customProviders.ts, examples/docs/streaming/streamedHITL.ts, examples/research-bot/main.ts, examples/tools/image-generation.ts
This pull request updates the examples to use `node:` prefix when it's necessary.
=> Consistently use node: prefix in example apps

.changeset/dull-beans-arrive.md, examples/docs/voice-agents/turnDetection.ts, packages/agents-realtime/src/clientMessages.ts, packages/agents-realtime/src/openaiRealtimeBase.ts, packages/agents-realtime/src/realtimeSession.ts
- inputAudioTranscription
- turnDetection
=> Improve the types of RealtimeSession configuration

.changeset/clever-tools-reply.md, packages/agents-core/src/usage.ts, packages/agents-core/test/usage.test.ts
This pull request resolves #124
=> Fix #124 by allowing an empty object for Usage#add method

.changeset/ten-lizards-deny.md, packages/agents-core/src/mcp.ts, packages/agents-core/test/mcpCache.test.ts
This PR changes the default for `cacheToolsList` from `true` to `false`. The documentation makes is sound like the default is `false` (see https://openai.github.io/openai-agents-js/guides/mcp/#other-things-to-know), and enabling caching has some unwanted side effects, especially when working with multiple local stdio MCP servers.
Defaulting to `false` is the safer option.
=> Do not cache the toolsList per default

.changeset/poor-regions-try.md, packages/agents-core/src/result.ts
This pull request resolves the issue reported at https://github.com/openai/openai-agents-js/issues/139#issuecomment-2998999137
=> Fix a bug where some of the exceptions thrown from runImplementation.ts could be unhandled

.changeset/shiny-berries-kiss.md, examples/docs/extensions/twilio-basic.ts, packages/agents-extensions/src/TwilioRealtimeTransport.ts, packages/agents-extensions/test/TwilioRealtimeTransport.test.ts, packages/agents-extensions/test/index.test.ts, packages/agents-realtime/package.json, packages/agents-realtime/src/openaiRealtimeWebsocket.ts, packages/agents-realtime/src/shims/shims-browser.ts, packages/agents-realtime/src/shims/shims-node.ts, packages/agents-realtime/src/shims/shims-workerd.ts, pnpm-workspace.yaml
the twilio websocket extension used the node `ws` specific apis for attaching event handlers, which made it throw in a cloudflare environment. this patch adds a fix to the types, and uses `.addEventListener` on the websocket instead of `.on`. this also adds a fix to load the right shim for workerd when using `@openai/agents-realtime`
=> fix: use web standard event apis for twilio websocket

.changeset/funny-memes-cover.md, docs/src/content/docs/guides/voice-agents/transport.mdx, docs/src/content/docs/ja/guides/voice-agents/transport.mdx, packages/agents-realtime/src/index.ts, packages/agents-realtime/src/openaiRealtimeBase.ts, packages/agents-realtime/src/transportLayer.ts, packages/agents-realtime/src/transportLayerEvents.ts, packages/agents-realtime/test/stubs.ts
Renamed all occurrences of `RealtimeTranportEventTypes` to `RealtimeTransportEventTypes`. Confirmed all tests pass. Resolves #166
=> fix: correct typo in RealtimeTransportEventTypes identifier

packages/agents-core/src/runState.ts, packages/agents-core/test/runState.test.ts
This pull request resolves #131
=> Fix #131 Human in the Loop MCP approval fails

.changeset/odd-rice-call.md, .github/workflows/test.yml, docs/package-lock.json, examples/agent-patterns/package.json, examples/ai-sdk/package.json, examples/basic/package.json, examples/customer-service/package.json, examples/docs/package.json, examples/financial-research-agent/package.json, examples/handoffs/package.json, examples/mcp/package.json, examples/model-providers/package.json, examples/nextjs/package.json, examples/realtime-next/package.json, examples/realtime-twilio/package.json, examples/research-bot/package.json, examples/tools/package.json, package.json, packages/agents-core/package.json, packages/agents-core/src/metadata.ts, packages/agents-extensions/package.json, packages/agents-extensions/src/metadata.ts, packages/agents-openai/package.json, packages/agents-openai/src/metadata.ts, packages/agents-realtime/package.json, packages/agents-realtime/src/metadata.ts, pnpm-lock.yaml
This pull applies a quick workaround of #187 for everyone; Ultimately, we should resolve the compatibility with the latest (more specifically 3.25.68 and any newer versions), but for now, this fix is crucial for onboarding with this SDK.
=> Tentative fix for #187 : Lock zod version to <=3.25.67 (prev: >=3.25.40 <4)

.changeset/tame-hotels-hope.md, .github/workflows/test.yml, packages/agents-core/src/tracing/provider.ts
This pull request resolves #175 and related reports. This commit https://github.com/openai/openai-agents-js/commit/25165dfe29de59014398dea503b4bf5282fb9d23 in #45 introduced system.exit calls, which didn't exist before the fix. So, reverting them should make sense. An alternative approach would be to introduce a new flag env variable to turn this on/off but I don't think it's necessary.
=> Fix #175 by removing system.exit calls in the built-in handlers

.changeset/twelve-poets-mate.md, packages/agents-core/src/run.ts, packages/agents-core/test/run.stream.test.ts
This change corrects a bug where the `agent_updated_stream_event` was emitting the stale `currentAgent` rather than the newly active agent after a handoff.  
- Updates `run.ts` to emit `result.state._currentAgent`  
- Adds a streaming test to verify the new agent is emitted  
- Includes a patch-level changeset for @openai/agents-core
Resolves #202
=> fix(core): emit correct agent in agent_updated_stream_event during streaming handoff

.changeset/silly-geese-wear.md, packages/agents-realtime/src/clientMessages.ts, packages/agents-realtime/src/openaiRealtimeBase.ts
Adds support for the speed parameter per https://platform.openai.com/docs/api-reference/realtime-sessions/session_object#realtime-sessions/session_object-speed
=> feat: support speed session configuration

.changeset/strong-lobsters-repair.md, packages/agents-extensions/src/TwilioRealtimeTransport.ts, packages/agents-extensions/test/TwilioRealtimeTransport.test.ts, packages/agents-extensions/test/index.test.ts, packages/agents-realtime/src/openaiRealtimeBase.ts, packages/agents-realtime/src/openaiRealtimeWebsocket.ts
Depending on the turn detection settings the Realtime API might cancel an ongoing response automatically which in the current code might run into occasional race conditions with the `this.#ongoingResponse` check which in turn causes errors.
This change shuffles the logic around so that if an interruption is happening because of turn detection it will check if the session config has cancellation of responses enabled and only cancel if not. For other interruption calls like guardrails or manual interruptions we will still perform an interruption. 
This change isn't needed in WebRTC because the turn detection based interruptions happen server side.
=> fix(realtime-ws): stop accidental cancellation error

.github/workflows/test.yml
workaround for https://github.com/pnpm/pnpm/issues/9743
=> Workaround for pnpm install error with node 24.4

.github/workflows/release.yml
Reverts openai/openai-agents-js#231
The root cause is that we are not using `changeset publish` for publishing and our custom publish command does `pnpm publish -r --no-git-checks`. In this case, the step outputs are empty, and there is no workaround so far.
@dkundel-openai was there any specific reason to avoid `changeset publish`? If `changeset publish` works, the following step to push tags should work.
=> Revert "Fix release tagging"

.github/workflows/release.yml
This pull request resolves #20 
Currently, this project does not block commit push to main branch by bot user, so it should work. That said, let's check if it really works when we make a new release next time.
=> Fix #20 Update metadata.ts files when releasing a new version

.changeset/open-candies-watch.md, packages/agents-core/src/mcp.ts, packages/agents-core/src/shims/mcp-server/browser.ts, packages/agents-core/src/shims/mcp-server/node.ts, packages/agents-core/test/mcpCache.test.ts
This pull request resolves #219
=> Fix #219 MCPServer#invalidateToolsCache() not exposed while being mentioned in the documents

.changeset/wise-cats-tell.md, packages/agents-realtime/src/realtimeSession.ts, packages/agents-realtime/test/realtimeSession.test.ts
Fixes a bug where `RealtimeSession` did not emit the `audio_start` event, despite it being defined in the type system.
- Emit `audio_start` once per turn when the first audio chunk arrives
- Reset internal `#audioStarted` flag on:
- `turn_started`
- `audio_done`
- `audio_interrupted`
- Added test to verify `audio_start` fires once per turn
- Aligns behavior with existing type definitions  and verified with pnpm build,test,lint
Resolves #235
=> fix: emit audio_start event when audio begins

.github/workflows/release-tag.yml, .github/workflows/release.yml, package.json
- customize the version script to include metadata.ts changes in changesets PR
- move git tag operation to a separate job
=> Improve the release operation jobs

.changeset/stale-times-bathe.md, packages/agents-openai/src/openaiResponsesModel.ts
Replaying a full run history with the `codeInterpreterTool` fails because the API’s `container_id` stayed in snake_case and never got mapped to `providerData.containerId`.  As such, I've added a small `snakeToCamelCase` helper so incoming `container_id` becomes `containerId`, and we still convert it back when building the next request. Now the container ID survives in history and a second `runner.run(...)` won’t throw “missing container_id” anymore.
Changes:
- new `snakeToCamelCase` utility  
- apply it in `convertToOutputItem`  
- continue converting back in `getInputItems`  
- unit tests for both directions  
With these changes, replaying the full `result.history` now succeeds on the second `runner.run(...)` and the `container_id` is correctly preserved across runs.
Resolves #253
=> fix: persist container_id in codeInterpreterTool history

.changeset/three-monkeys-bake.md, packages/agents-core/src/mcp.ts, packages/agents-core/src/shims/mcp-server/node.ts
Some MCP operations may timeout when execution takes too long. In such cases, we want to be able to customize the timeout duration to ensure MCP can execute successfully.
=> feat: add timeout parameter to mcp callTool

.changeset/two-bats-judge.md, examples/mcp/package.json, examples/mcp/sse-example.ts, packages/agents-core/src/index.ts, packages/agents-core/src/mcp.ts, packages/agents-core/src/shims/mcp-server/browser.ts, packages/agents-core/src/shims/mcp-server/node.ts, packages/agents-core/src/shims/shims-browser.ts, packages/agents-core/src/shims/shims-node.ts
MCP SSE server transport support close #289
=> feat: add sse server implementation for mcp client

.changeset/cool-cloths-fry.md, packages/agents-core/src/usage.ts, packages/agents-core/test/usage.test.ts, packages/agents-openai/test/openaiChatCompletionsModel.test.ts
Restores OpenAI token usage counts in `RunContext.usage` by teaching the Usage class to consume the existing snake_case fields from API responses. Previously, Usage only looked for camelCase props and silently dropped all prompt_tokens, completion_tokens, and total_tokens.
`RunContext.usage` will now accurately reflect both request counts and aggregated token usage across single or multi-step agent runs.
Resolves #298
=> fix(usage): handle OpenAI snake_case usage fields (#298)

.changeset/preserve-audio-formats-on-agent-update.md, packages/agents-realtime/src/realtimeSession.ts, packages/agents-realtime/test/realtimeSession.test.ts
This pull request fixes a critical bug where updating the agent in a `RealtimeSession` would cause important session config fields (such as `inputAudioFormat` and `outputAudioFormat`) to revert to defaults, breaking integrations like Twilio that require specific audio formats.
Fixes #317 
When calling `updateAgent()`on a `RealtimeSession`, the session config was rebuilt from a minimal set of fields, omitting values like `inputAudioFormat`, `outputAudioFormat`, `modalities`, `speed`, etc.
This caused the server to fall back to defaults (e.g., `pcm16`), resulting in loud static or broken audio for Twilio and other integrations that require a specific format.
Create a `RealtimeSession` with a custom `inputAudioFormat` (e.g., `g711_ulaw`).
Call `updateAgent()` to switch to a new agent. …
=> fix(realtime-session): preserve audio format and config fields on agent update

.changeset/purple-chicken-protect.md, docs/src/content/docs/guides/mcp.mdx, docs/src/content/docs/ja/guides/mcp.mdx, examples/mcp/streamable-http-custom-fetch-example.ts, packages/agents-core/package.json, packages/agents-core/src/mcp.ts, packages/agents-core/src/shims/mcp-server/node.ts, pnpm-lock.yaml
This enhancement improves the flexibility of the StreamableHTTPClientTransport class by enabling the injection of a custom fetch implementation. This change empowers users to exert fine-grained control over network requests, facilitating advanced use cases such as custom authentication flows, specialized request handling, and improved adaptability of the transport layer.
Key improvements:
- Added optional 'fetch' parameter to MCPServerStreamableHttpOptions interface
- Updated NodeMCPServerStreamableHttp implementation to pass custom fetch to underlying transport
- Enables custom authentication flows for corporate environments
- Supports request/response logging and debugging capabilities
- Allows retry logic implementation for unreliable connections
- Facilitates testing with mock fetch …
=> Add custom fetch support to StreamableHTTP MCP transport

.husky/pre-commit
Fixes: https://github.com/openai/openai-agents-js/issues/311
=> feat: update helper message when trufflehog not found on system

packages/agents-core/src/tracing/processor.ts
Closes: #361 
This will conditionally append the groupId to the console output only when it's present (not null).
=> fix(tracing): include groupId in trace export log message

.changeset/fix-streaming-agent-end-lifecycle.md, packages/agents-core/src/run.ts, packages/agents-core/test/run.stream.test.ts, packages/agents-core/test/run.test.ts
Fixes #371 - Streaming agents do not call the agent_end lifecycle hook
- Fix streaming agents not calling agent_end lifecycle hook when completing execution
- Add agent_end event emissions in streaming loop to match non-streaming behavior  
- Add tests to verify agent_end events are emitted for both streaming and non-streaming agents
- Resolves issue where users could not collect usage information from streaming agent runs
Users reported that `agent_end` lifecycle hooks work for non-streaming agents but are never called for streaming agents, preventing them from collecting usage information at the end of agent runs.
Added missing `agent_end` event emissions in the streaming implementation (`packages/agents-core/src/run.ts`) to match the non-streaming behavior. Both the runner and agent …
=> fix: emit agent_end lifecycle event for streaming agents

.changeset/pink-moles-travel.md
As you can see at https://github.com/openai/openai-agents-js/pull/357, `@openai/agents` package has only patch upgrades, so if we go with the current list of changeset files, the package with be 0.0.18 while others are 0.1.0. This pull request makes the versioning consistent for the upcoming release.
=> Add a changeset to consistenly bump minor versions for all packages

.changeset/config.json, .changeset/wicked-snails-camp.md, packages/agents-extensions/package.json, pnpm-lock.yaml
This pull request aims to resolve the unexpected major bump behavior of the changesets like this one: https://github.com/openai/openai-agents-js/pull/386
I've added an experimental option to better control this versioning policy for us: https://github.com/changesets/changesets/blob/%40changesets/config%403.1.1/docs/experimental-options.md plus added `@openai/agents` the `linked` list to aign versioning with other packages.
Also, `@openai/agents-extensions` depends on `@openai/agents`, which brings all the sub packages. This results in the major bump for `@openai/agents-extensions` at least. Therefore, I loosen the versioning range for the package.
=> Fix changeset configuration to follow consistent minor version bumps

.changeset/nervous-windows-raise.md, AGENTS.md, README.md, docs/README.md, docs/src/content/docs/guides/agents.mdx, docs/src/content/docs/guides/config.mdx, docs/src/content/docs/guides/tools.mdx, docs/src/content/docs/guides/voice-agents/quickstart.mdx, docs/src/content/docs/ja/guides/config.mdx, examples/docs/readme/readme-voice-agent.ts, packages/agents-core/src/runContext.ts, packages/agents-core/test/tracing.test.ts, packages/agents-realtime/src/openaiRealtimeWebRtc.ts, packages/agents-realtime/src/realtimeSession.ts, packages/agents/README.md
This pull request improves the docs/comments' consistencies using Codex. I've reviewed all the suggested changes and adjusted some of them.
=> Make docs and comments more consistent using Codex

docs/src/content/docs/extensions/ai-sdk.mdx
This document update will be merged after we release a new version including #356 changes
=> Update ai-sdk document page after releasing #356

docs/src/content/docs/guides/human-in-the-loop.mdx
Hey,
Just noticed this link in the docs was giving a 404 while browsing this page: https://openai.github.io/openai-agents-js/guides/human-in-the-loop/
The correct link appears to be https://openai.github.io/openai-agents-js/guides/results
=> fix(docs): fix link to results in human-in-the-loop guide

.changeset/sharp-planets-rescue.md, packages/agents-realtime/src/openaiRealtimeBase.ts
with the current implementation, the initial tracing (workflow name and metadata) wasn't taking into account, it was rejecting configuration update even if there wasn't one set.
=> fix: allow setting an initial tracing configuration for Realtime

.changeset/tasty-wings-fry.md, packages/agents-core/src/shims/shims-workerd.ts
This is simple, it just enables MCP support for workerd/cloudflare workers. I did some basic tests and it seemed to work just fine!
=> feat: enable mcp exports for cloudflare workers

.changeset/easy-rivers-build.md, packages/agents-core/src/runImplementation.ts, packages/agents-core/src/tool.ts, packages/agents-realtime/src/realtimeSession.ts
The feature request #412 is valid, so we may want to add further information to function tool execution if a developer needs. This changes do not break any existing apps.
=> feat: Fix #412 add optional details data to function tool execution

docs/src/content/docs/guides/agents.mdx, examples/docs/agents/agentsAsTools.ts
This pull request updates the document to align with https://github.com/openai/openai-agents-python/pull/1650
=> docs: Update Agents docs to align with Python SDK

docs/src/content/docs/guides/models.mdx
**Summary:** Update the models guide to show GPT‑5 settings inside the providerData object so provider-specific options are placed in the correct location.
**Changes:** edit docs/src/content/docs/guides/models.mdx to demonstrate modelSettings.providerData.
**Example:** see example usage in examples/basic/hello-world-gpt-5.ts (shows modelSettings.providerData and an OpenAIChatCompletionsModel example).
**Impact:** docs-only change; no changeset required.
=> GPT‑5 model settings under providerData

.changeset/selfish-geckos-run.md, packages/agents-realtime/src/openaiRealtimeWebRtc.ts, packages/agents-realtime/test/openaiRealtimeWebRtc.test.ts
Resolves #483
I exposed the WebRTC Call ID - included in the response headers in the /calls API call - as a WebRTCState attribute and getter.
=> fix: #483 expose Call ID in OpenAIRealtimeWebRTC

.changeset/warm-ties-sort.md, examples/agent-patterns/agents-as-tools.ts, packages/agents-core/src/agent.ts, packages/agents-core/test/agent.test.ts
This pull request resolves #460; See the updated examples to learn how the new options could be used. I will come up with a similar PR for Python SDK.
=> feat: #460 Enable to customize the internal runner for an agent as too

.changeset/all-mangos-send.md, packages/agents-realtime/src/clientMessages.ts, packages/agents-realtime/test/realtimeVoiceConfigRegression.test.ts
This pull request resolves #495
=> fix: #495 Realtime session config falls back to legacy format when voice is set

examples/agent-patterns/llm-as-a-judge.ts, examples/agent-patterns/routing.ts, examples/basic/chat.ts, examples/docs/results/historyLoop.ts, examples/docs/running-agents/chatLoop.ts, examples/nextjs/src/app/api/basic/route.ts
Corrects AgentInputItem imports in documentation examples to use import type
- Running agents guide: chat-threads
- Any example code that imports AgentInputItem
This is a documentation/examples fix only; no runtime behavior changes. This fixes #277.
=> fix(examples): correct AgentInputItem import type usage in examples

.changeset/cloudflare-fetch-upgrade.md, packages/agents-extensions/src/CloudflareRealtimeTransport.ts, packages/agents-extensions/src/index.ts, packages/agents-extensions/test/CloudflareRealtimeTransport.test.ts, packages/agents-realtime/src/openaiRealtimeWebsocket.ts
- Adds `useWorkersFetchUpgrade` option to `OpenAIRealtimeWebSocket` for Cloudflare/workerd ([Cloudflare Workers: WebSockets — Make outbound WebSocket connections](https://developers.cloudflare.com/workers/runtime-apis/websockets/)).
- Implements `connectViaFetchUpgrade()` to establish WS via `fetch()` + `Upgrade: websocket` (see same docs above).
- Keeps default constructor-based WebSocket path unchanged for other environments.
Cloudflare Workers and other workerd runtimes (e.g., Miniflare) cannot create client WebSockets via the global `WebSocket` constructor. Instead, Cloudflare’s documentation specifies using an HTTP `fetch()` upgrade flow that returns `response.webSocket`, which must be `accept()`ed ([docs](https://developers.cloudflare.com/workers/runtime-apis/websockets/)). This PR …
=> feat(agents-realtime): add fetch-based WebSocket upgrade for Cloudflare/workerd

docs/astro.config.mjs, docs/src/content/docs/extensions/cloudflare.mdx, docs/src/content/docs/guides/troubleshooting.mdx, docs/src/content/docs/guides/voice-agents/transport.mdx, docs/src/content/docs/ja/extensions/cloudflare.mdx, docs/src/content/docs/ja/guides/voice-agents/transport.mdx, docs/src/content/docs/zh/extensions/cloudflare.mdx, docs/src/content/docs/zh/guides/voice-agents/transport.mdx, examples/docs/extensions/cloudflare-basic.ts
This pull request is the documentation for what we implemented in #502 .
* add Cloudflare Workers transport guide and localizations
* surface the guide within navigation, troubleshooting, and voice transport docs
* publish a reusable example for configuring the Cloudflare realtime transport
* pnpm lint
=> docs: add Cloudflare Workers transport guide

docs/src/content/docs/guides/models.mdx, docs/src/content/docs/ja/guides/models.mdx, docs/src/content/docs/zh/guides/models.mdx, examples/docs/models/gpt5DefaultModelSettings.ts
This pull request updates the docs once #513 is released
=> Document updates for #513

.changeset/loud-bags-enter.md, examples/agent-patterns/README.md, examples/agent-patterns/agents-as-tools-conditional.ts, examples/agent-patterns/package.json, examples/handoffs/README.md, examples/handoffs/is-enabled.ts, examples/handoffs/package.json, package.json, packages/agents-core/src/agent.ts, packages/agents-core/src/handoff.ts, packages/agents-core/src/index.ts, packages/agents-core/src/run.ts, packages/agents-core/src/runImplementation.ts, packages/agents-core/src/tool.ts, packages/agents-core/src/utils/serialize.ts, packages/agents-core/test/agent.test.ts, packages/agents-core/test/handoffs.test.ts, packages/agents-core/test/tool.test.ts, packages/agents-realtime/src/realtimeSession.ts
This pull request resolves #478
=> feat: #478 add isEnabled to handoffs & agents as tools

.changeset/cuddly-states-begin.md, packages/agents-core/src/agent.ts, packages/agents-core/test/agent.test.ts
This pull request improves the clarity of the behavior of agents w/ stopAtToolNames as tools; I was initially going to add warn-level logging, but it could be a noise for some edge cases. So, I've set the logging level to debug for now. We may revisit this in the future.
resolves #247 (for now)
=> fix: #247 logging for a sub-agent w/ stopAtToolNames

.changeset/wet-snakes-stare.md, packages/agents-realtime/src/realtimeSession.ts, packages/agents-realtime/test/realtimeSession.test.ts
This pull request resolves #494; this affects not only the demo app but any apps, so we should deliver this change shortly
=> fix: #494 Voice input transcription failing in realtime-demo

.changeset/add-korean-docs.md, docs/astro.config.mjs, docs/src/scripts/translate.ts
This PR includes the following:
- Korean translations config + translation prompts
=> Korean translations

docs/src/content/docs/guides/voice-agents/quickstart.mdx, docs/src/content/docs/ja/guides/voice-agents/quickstart.mdx, docs/src/content/docs/ko/guides/voice-agents/quickstart.mdx, docs/src/content/docs/zh/guides/voice-agents/quickstart.mdx
Align import path references for consistency in the voice agents quickstart guides.
- Before: `import { RealtimeAgent } from '@openai/agents-realtime'`
- After: `import { RealtimeAgent } from '@openai/agents/realtime'`
- Before: `import { RealtimeSession } from '@openai/agents-realtime'`
- After: `import { RealtimeSession } from '@openai/agents/realtime'`
- Docs-only change. No runtime code affected.
- Applies to en/ja/ko/zh quickstart pages.
=> docs: fix import path typos in Voice Agents Quickstart

.changeset/bumpy-cats-run.md, packages/agents-realtime/src/openaiRealtimeWebsocket.ts, packages/agents-realtime/test/openaiRealtimeWebsocket.test.ts
This pull request resolves #552; https://github.com/openai/openai-agents-js/pull/324 did great job for mitigating the issue, but the fix was incomplete.
=> fix: #552 WebSocket Realtime Agent: invalid_request_error with decimal audio_end_ms data

.changeset/young-bars-hide.md, examples/basic/prompt-id.ts, packages/agents-openai/src/openaiResponsesModel.ts, packages/agents-openai/test/openaiResponsesModel.test.ts
this pull request resolves #562; i confirmed the behavior using a few examples as well; probably python sdk should have the same issue; i will send a pull request to python repo later on.
=> fix: #562 invalid model settings when prompt is set in Agent
